### ISSUE TITLE
Having encountered fatal error in running inference on Segmentation task: ADE20K

### ISSUE THREAD

**Issue by GivemeACOG** [wl-zhao/VPD#16]
Here my GPU is GTX1080
GPU Driver: NVIDIA-SMI 470.182.03   Driver Version: 470.182.03   CUDA Version: 11.4
PyTorch:  1.11.0 
Python:    3.8.5
It seems that something went wrong with the parallel training, but I'm not sure.
Having followed the instructions step by step.

=============================================================
Traceback (most recent call last):
  File "./test.py", line 11, in <module>
    from mmcv.cnn.utils import revert_sync_batchnorm
ImportError: cannot import name 'revert_sync_batchnorm' from 'mmcv.cnn.utils' (/home/ycy/anaconda3/envs/ldm/lib/python3.8/site-packages/mmcv/cnn/utils/__in$t__.py)
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 6417) of binary: /home/ycy/anaconda3/envs/ldm/bin/python3
Traceback (most recent call last):
  File "/home/ycy/anaconda3/envs/ldm/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/ycy/anaconda3/envs/ldm/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ycy/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/ycy/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/ycy/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/ycy/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/distributed/run.py", line 715, in run
    elastic_launch(
  File "/home/ycy/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/ycy/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================

**Comment by wl-zhao** [comment]
It seems that something is wrong with the mmcv package.  Could you please provide more details about your mmcv version?

**Comment by wl-zhao** [comment]
We have tested our code with `mmcv==1.7.1` and `mmsegmentation==1.0.0`.
